config/routes.rb
QuoteEngine::Application.routes.draw do
	resources :quotes
	resources :sources
	resources :categories
	get 'quotes' => 'quotes#index', :as => 'admin'
  root :to => "home#show"
end

app/models/category.rb
class Category < ActiveRecord::Base
	# Mass-Assignment protection
  attr_accessible :name

  # Relationships
  has_many :quotes

  # Validations
  validates_uniqueness_of :name

  # Pagination
  paginates_per 50

  def to_s
  	name
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	# Mass Assignment Protection
  attr_accessible :content, :context, :source_id, :category_id

  # Relationships
  belongs_to :source
  belongs_to :category

  # Validations
  validates_presence_of :content, :source, :category

  # Pagination
  paginates_per 50

  def to_s
  	content
  end

  def self.search(term)
  	if term
  		where("content LIKE ?", "% #{term} %")
  	else
  		scoped
  	end
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
	# Mass-Assignment protection
	attr_accessible :bio, :first_name, :middle_name, :official_name, :title

	# Relationships
	has_many :quotes, :dependent => :destroy

	# Validations
	validates_presence_of :official_name

	def to_s
		full_name
	end

	def full_name
		[title, first_name, middle_name, official_name].join(' ')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  def index
  	@categories = Category.order('name ASC').page(params[:page])
  end

  def show
  	@category = Category.find(params[:id])
    @quotes = @category.quotes.joins(:source).sorted(params[:sort], "official_name ASC").page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    if @category = Category.create( params[:category] )
      redirect_to categories_path, :notice => 'Category added successfully.'
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find( params[:id] )
  end

  def update
    if @category = Category.update_attributes( params[:category] )
      redirect_to categories_path, :notice => 'Category updated successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find( params[:id] )
    @category.destroy
    redirect_to categories_path, :notice => 'Category deleted.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	before_filter :authenticate, :except => [:index, :show]

	def index
		@quotes = Quote.joins(:source,:category).search(params[:search]).sorted(params[:sort], "official_name ASC").page(params[:page])
	end

	def show
		@quote = Quote.find( params[:id] )
	end

	def new
		@quote = Quote.new
	end

	def create
		if @quote = Quote.create( params[:quote] )
			redirect_to quotes_path, :notice => 'Quote added successfully.'
		else
			render 'new'
		end
	end

	def edit
		@quote = Quote.find( params[:id] )
	end

	def update
		if @quote = Quote.update_attributes( params[:quote] )
			redirect_to quotes_path, :notice => 'Quote updated successfully.'
		else
			render 'edit'
		end
	end

	def destroy
		@quote = Quote.find( params[:id] )
		@quote.destroy
		redirect_to quotes_path, :notice => 'Quote deleted.'
	end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  def index
  	@sources = Source.order('official_name ASC').page(params[:page])
  end

  def show
  	@source = Source.find(params[:id])
    @quotes = @source.quotes.joins(:category).sorted(params[:sort], "name ASC").page(params[:page])
  end

  def new
    @source = Source.new
  end

  def create
    if @source = Source.create( params[:source] )
      redirect_to sources_path, :notice => 'Source added successfully.'
    else
      render 'new'
    end
  end

  def edit
    @source = Source.find( params[:id] )
  end

  def update
    if @source = Source.update_attributes( params[:source] )
      redirect_to sources_path, :notice => 'Source updated successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @source = Source.find( params[:id] )
    @source.destroy
    redirect_to sources_path, :notice => 'Source deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, :html => {:class=>'standard'} do |f|
	= f.input :name
	= f.submit

app/views/categories/edit.html.haml
%h1 Edit Category
= render 'form'

app/views/categories/index.html.haml
= title "All Categories"

%h1
	Categories
	%small= link_to 'Add new', new_quote_path if admin?

%table
	%thead
		%tr
			%th Name
			%th Quotes
			- if admin?
				%th
	%tbody
		- @categories.each do |cat|
			%tr
				%td= link_to cat.name, cat
				%td= cat.quotes.count
				- if admin?
					%td
						= link_to 'Edit', edit_category_path(cat), :class => 'small button'
						= link_to 'Delete', cat, :method => :delete, :confirm => 'Are you sure?', :class => 'small danger button'

= paginate @categories

app/views/categories/new.html.haml
%h1 New Category
= render 'form'

app/views/categories/show.html.haml
= title @category.to_s
%h1
	= @category.name
	%small= pluralize( @category.quotes.count, 'quotes' )
%table
	%thead
		%tr
			%th Quote
			%th Context
			%th= link_to_sorted 'Source', :official_name
	%tbody
		- if @quotes
			- @quotes.each do |quote|
				%tr
					%td= quote.content
					%td= quote.context
					%td= link_to quote.source, quote.source

app/views/home/show.html.haml
= title "Home"

.home
	%h1 Quotes for Urbanists
	%p
		Memorable thoughts on urbanism, civics, and the environment.


	.start
		= form_tag quotes_path, :method => :get do
			= label_tag :search, 'Start Here:'
			= text_field_tag :search, params[:search]
			= submit_tag 'Search', :name => nil

	%p
		Or,
		= link_to('browse all quotes',quotes_path) + '.'

app/views/layouts/_footer.html.haml
%footer
	%p
		A collaboration between
		= link_to "Fourth Environment, LLC", "http://www.fourthenvironment.com"
		and
		= link_to("Mouzon Design", "http://www.mouzon.com") + "."
		= "Website ©" + Time.now.year.to_s + "."
		All quotes are public domain, though we appreciate your linking to us as the source.
	%p
		- if admin?
			= link_to "Admin Logout", logout_path
		- else
			= link_to "Admin Login", login_path

app/views/layouts/_header.html.haml
%header
	= flash_messages
	%nav#primary
		%h1 Menu ▸ 
		%ul
			%li= link_to "Home", root_path
			%li= link_to "Quotes", quotes_path
			%li= link_to "Sources", sources_path
			%li= link_to "Categories", categories_path

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title
			= content_for(:title)
			Quote Engine
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= javascript_include_tag "//use.typekit.net/uyz6wtj.js"
		:javascript
			try{Typekit.load();}catch(e){}
		= csrf_meta_tags			
	%body
		= render 'layouts/header'
		%section#main= yield
		= render 'layouts/footer'
		:javascript
			var _gauges = _gauges || [];
			(function() {
				var t   = document.createElement('script');
				t.type  = 'text/javascript';
				t.async = true;
				t.id    = 'gauges-tracker';
				t.setAttribute('data-site-id', '507ef99f613f5d1a8d0000bc');
				t.src = '//secure.gaug.es/track.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(t, s);
			})();

app/views/quotes/_form.html.haml
= simple_form_for @quote, :html => { :class => 'stacked' } do |f|
	.input
		= f.association :source, :label_method => :full_name, :wrapper => false
		= link_to "Add a Source", new_source_path

	.input
		= f.association :category, :wrapper => false
		= link_to "Add a Category"

	= f.input :content
	= f.input :context
	= f.submit

app/views/quotes/_search.html.haml
.search
	= form_tag quotes_path, :method => :get do
		.box
			= label_tag :search, 'Keyword Search'
			= text_field_tag :search, params[:search]
		.buttons
			= submit_tag 'Search', :name => nil
			= link_to 'Clear', quotes_path, :class => 'button'
		%span.results= pluralize(@quotes.total_count, 'results') if params[:search]

app/views/quotes/edit.html.haml
%h1 Edit a Quote
= render 'form'

app/views/quotes/index.html.haml
= title "Quotes"

%h1
	All Quotes
	%small= link_to 'Add New', new_quote_path if admin?

= render 'quotes/search'

.quotes
	.quote.heading
		.content Quote
		.context Context
		.source= link_to_sorted "By", :official_name
		.category= link_to_sorted "Category", :name
		- if admin?
			.controls &nbsp;
	- @quotes.each do |quote|
		.quote
			.content= quote.content
			.context= quote.context
			.source= link_to quote.source, quote.source
			.category= link_to quote.category, quote.category
			- if admin?
				.controls
					= link_to 'Edit', edit_quote_path(quote), :class => 'small button'
					= link_to 'Delete', quote, :method => :delete, :confirm => 'Are you sure?', :class => 'small danger button'

= paginate @quotes

app/views/quotes/new.html.haml
%h1 Add a Quote
= render 'form'

app/views/quotes/show.html.haml
%h1
	Quote
	%small
		by
		= link_to @quote.source, @quote.source

%p
	%blockquote= @quote.content
%p
	From:
	= @quote.context
%p
	Filed under:
	= link_to @quote.category, @quote.category

app/views/sources/_form.html.haml
= simple_form_for @source, :html => {:class=>'standard'} do |f|
	= f.input :official_name, :hint => "Group, organization, or an individual's last name."
	= f.input :middle_name
	= f.input :first_name
	= f.input :title, :hint => "An important honorarium, like 'Sir', or 'Admiral'"
	= f.input :bio, :hint => "Any biographical information, like 'Politician (1759-1822)', or 'Director of Planning for Somewhere, US'"
	= f.submit

app/views/sources/edit.html.haml
%h1 Edit Source
= render 'form'

app/views/sources/index.html.haml
= title "All Sources"

%h1
	Sources
	%small= link_to 'Add new', new_source_path if admin?

%table
	%thead
		%tr
			%th Name
			%th Bio
			%th Quotes
			- if admin?
				%th
	%tbody
		- @sources.each do |source|
			%tr
				%td= link_to source.full_name, source
				%td= source.bio
				%td= source.quotes.count
				- if admin?
					%td
						= link_to 'Edit', edit_source_path(source), :class => 'small button'
						= link_to 'Delete', source, :method => :delete, :confirm => 'Are you sure?', :class => 'small danger button'

= paginate @sources

app/views/sources/new.html.haml
%h1 New Source
= render 'form'

app/views/sources/show.html.haml
= title @source.to_s
%h1
	= @source.full_name
	%small= pluralize( @source.quotes.count, 'quotes' )
.bio= @source.bio
%table
	%thead
		%tr
			%th Quote
			%th Context
			%th= link_to_sorted "Category", :name
	%tbody
		- if @quotes
			- @quotes.each do |quote|
				%tr
					%td= quote.content
					%td= quote.context
					%td= link_to quote.category, quote.category